# Generated by Django 3.1.7 on 2021-04-13 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph1',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph10',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph2',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph3',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph4',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph5',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph6',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph7',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph8',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='paragraph9',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 13, 11, 52, 28, 294596)),
        ),
    ]
